### ISSUE TITLE
activedirectory vs ldapjs - modification API

### ISSUE THREAD

**Issue by denis-aes** [gheeres/node-activedirectory#100]
First of all, thank you for good open source module. That's great. )

I'd like to clarify difference about your module and ldapjs one.

Because I want to modify AD information, and as I understood - ldapjs can modify, but has no auth, and you module can auth, but can't modify info?

This is confusing for me. Could you tell, what can I use for my purposes - to give self-management possibilities for company active directory users?

**Comment by gheeres** [comment]
This module has a dependency on [ldapjs](https://github.com/mcavage/node-ldapjs). You can think of it as a convenience wrapper around that library for Microsoft's implementation of LDAP. Everything that the [ActiveDirectory](https://github.com/gheeres/node-activedirectory) module does, you can do with [ldapjs](https://github.com/mcavage/node-ldapjs) and more.

Currently the [ActiveDirectory](https://github.com/gheeres/node-activedirectory) modules does not support modification of the directory contents. **A pull request would be graciously accepted** if anyone wants to tackle it. Optionally, you could [contract me](http://blog.heeresonline.com/consulting/) to do the work depending on your time frame and requirements.

>  ldapjs can modify, but has no auth, and you module can auth, but can't modify info?

[ldapjs](https://github.com/mcavage/node-ldapjs) does have authentication. It's the bind() function which is how you authenticate to LDAP servers.

>This is confusing for me. Could you tell, what can I use for my purposes - to give self-management possibilities for company active directory users?

If you need to edit, you **MUST** use [ldapjs](https://github.com/mcavage/node-ldapjs). But that doesn't preclude you from using both modules. Use activedirectory for reading contents, but use [ldapjs](https://github.com/mcavage/node-ldapjs) for write operations. Most applications read data several orders of magnitude more than they write. 

If this was my project I was working on, I'd probably break my code into two different interfaces / services, one to handle the reading and one to handle writing. That gives you the most flexibility without having to completely reinvent the wheel.

You'll also likely need to do some reading of the [LDAP specification](https://tools.ietf.org/html/rfc4511) and Microsoft's implementation of it (along with their custom extensions, etc.) so that you understand what is going on, etc.
