### ISSUE TITLE
AcceptSecurityContext error

### ISSUE THREAD

**Issue by irom77** [gheeres/node-activedirectory#101]
I'm getting error below: 
ERROR: {"dn":"","code":49,"name":"InvalidCredentialsError","message":"80090308: LdapErr: DSID-0C0903A9, comment: AcceptSecurityContext error, data 52e, v1db1\u0000"}

Btw 'userExists' gives me results 'true'

**Comment by gheeres** [comment]
Typically this is due to invalid username and/or password. When specifying usernames for authentication, make sure that you have a full userPrincipalName (i.e. user@domain.com) specified. This applies to the authenticate() method as well as the config object specified when creating your ActiveDirectory object.

Do you have some sample code? Please obfuscate and passwords or confidential data. Aside from the authenticate() method, all other functions MUST have a username / password specified in the config option.

**Comment by irom77** [comment]
Right..added @domain to actual username (not config) and it works great , sorry to bother you. At first I just pasted example with user without domain suffix and it didn't work. All set now, thnx

**Comment by jjayaraman** [comment]
Is it possible to use the username without the domain name? 
i.e. user instead of user@domain.com

Are there any configurations possible for this functionality?

**Comment by pgqueme** [comment]
In my case, adding the @domain at the end of the username worked.
