### ISSUE TITLE
Return all attributes by default

### ISSUE THREAD

**Issue by denis-aes** [gheeres/node-activedirectory#102]
Currently documentation contains this text:

**Optional Parameters / Extended Functionality**
*attributes - attributes to select and return (if these are set, the server will return only these attributes). Defaults to the empty set, which means all attributes.*

This is misleading. Because really only predefined inside library attributes would be returned.

In other part of docs we see:

**Attributes**
*By default, the following attributes are returned for users and groups:
user - distinguishedName, userPrincipalName, sAMAccountName, mail, lockoutTime, whenCreated, pwdLastSet, userAccountControl, employeeID, sn, givenName, initials, cn, displayName, comment, description*

This is true. But to my sorrow this means - there is no real way to get all available attrs from ldapjs.

I suggest to make available to send empty attrs list to ldapjs to get really full set of existing attrs from AD.

**Comment by denis-aes** [comment]
I suggest following changes
1. default attributes list - this should be set to empty list, or suggested as recommended list
2. currently cn, dn, objectCategory are added to attributes list - this should be added only if attrs list is not empty

**Comment by gheeres** [comment]
The early version of the library supported that but was accidentally dropped over time as people needed the ability to pass in custom attributes per query.

Please pull / test latest version from git. If this solves your problem, let me know and I will push a new version. 

Note: All of my [unit/integration tests](https://github.com/gheeres/node-activedirectory/tree/master/test) are passing. If you still have an error condition, please submit a unit test to replicate the problem.

>I suggest following changes
>1. default attributes list - this should be set to empty list, or suggested as recommended list

No. You can override the default list of attributes in your configuration object if you prefer "everything". The more attributes included in queries, the more overhead over the network and in processing, memory utilization, etc.

You can set it now to an empty array, or specify an array with a wildcard.

```javascript
var opts = {
  // attributes: [ ]
  attributes: [ '*' ]
}
```

>2. currently cn, dn, objectCategory are added to attributes list - this should be added only if attrs list is not empty

These attributes have to be added in order to be able to do group queries (i.e. includeMembership). In the past, users have specified their own simple / short list attributes for a find() operation but wanted group membership included. Those attributes supplied by the user omitted the attributes necessary to chase groups. The code was updated to include these by default if omitted so that membership inclusion would work as expected and users didn't have to remember that they were needed, etc. The extra attributes should be omitted in the result returned from the library.

**Comment by bthaase** [comment]
Came here looking for this exact issue, confirmed the latest changes seem to be working for me. Thank you!

**Comment by gheeres** [comment]
bthaase, thanks for confirming this worked.
