### ISSUE TITLE
findUsers syntax?

### ISSUE THREAD

**Issue by gCurtisCT** [gheeres/node-activedirectory#107]
I'm new to ldap

I'm using the "in-memory server" from this page: http://ldapjs.org/examples.html

I can do   

    dapsearch -H ldap://localhost:1389 -LLL -x -D cn=root -w secret -b "cn=ldapjs, ou=users, o=joyent"
And get back  

    dn: cn=ldapjs, ou=users, o=joyent
    cn: ldapjs
    description: Created via ldapadd
    objectclass: unixUser
    shell: /bin/bash

But when I do this:

```
var ActiveDirectory = require('activedirectory');
var config = { url: 'ldap://localhost:1389',
               baseDN: 'o=joyent',
               username: 'cn=root',
               password: 'secret'
             }
var ad = new ActiveDirectory(config);

ad.authenticate(config.username, config.password, function(err, auth) {
  if (err) {
    console.log('ERROR: '+JSON.stringify(err));
    return;
  }

  if (auth) {
    console.log('Authenticated!');


    var query = 'cn=ldapjs, ou=users, o=joyent';

    var ad = new ActiveDirectory(config);
    ad.findUsers(query, true, function(err, users) {
      if (err) {
        console.log('ERROR: ' +JSON.stringify(err));
        return;
      }

      if ((! users) || (users.length == 0)) console.log('No users found.');
      else {
        console.log('findUsers: '+JSON.stringify(users));
      }
    });

  }
  else {
    console.log('Authentication failed!');
  }
});
```

It comes out with 
````ERROR: {"dn":"o=joyent","code":32,"name":"NoSuchObjectError","message":"o=joyent"}````

What am I doing wrong?

**Comment by gheeres** [comment]
Your ldapsearch is working by "accident". The -b parameter actually specifies what the "baseDN" or root node to search from or within. 

```
usage: ldapsearch [options] [filter [attributes...]]
...
  -b basedn  base dn for search
```

Instead of using a full path / DN just specify the attribute(s) you're searching for when using the findUsers() method. 

```javascript
var query = 'cn=ldapjs';
```

You'll want to read and learn more about how [ldap search filters](https://msdn.microsoft.com/en-us/library/aa746475(v=vs.85).aspx) are constructed.

As per the documentation, the findUsers() method will expand the query provided, adding the following additional critieria:

```
 (&(|(objectClass=user)(objectClass=person))(!(objectClass=computer))(!(objectClass=group)))
```

If you want more control over your query (i.e. specify the full query), then you can use the raw find() method or optionally override the default filter by using the opts object.
