### ISSUE TITLE
ECONNREFUSED happening consistently

### ISSUE THREAD

**Issue by bibodha** [gheeres/node-activedirectory#115]
I am trying to call findUser and to find the group membership to look for a particular group that the user should belong to. This code is working on windows but when I run it on a Mac, I consistently get ECONNREFUSED or ECONNRESET (more ECONNREFUSED than ECONNRESET) I turned on logging and I see that it is finding the groups but it still gives me the error. I also tried calling isUserMemberOf and I still get the ECONNREFUSED error. Any ideas as why this might consistently work on windows but not on a mac? I also have this app pushed to a docker container and it fails there as well. We do have 1000+ users in our AD and we have multiple nested groups. Is it because it's making to many calls too fast? Is there a way to throttle it? 

Mac OSX - 10.10.5
Node - v4.2.0
NPM - v2.14.7
Activedirectory - v0.7.1
ldapjs - v1.0.0

**Comment by gheeres** [comment]
Can you provide some example code to reproduce the problem? I've never tested the module on a Mac but the majority of my development for this module is done on Linux which shares a lot of similarities with Mac OS.

Without code available, my guess would be that there are too many requests being made to the server and it is actively refusing them. What type of hardware and resources are on your domain controller? Are there any query restricts or limits on the server (either on the server or "in front" of the server? Have you monitored your domain controller CPU and memory usage to see if there are any anomalies, etc.

There isn't currently any throttling within the module. Group enumeration is an "expensive" operation and should not be done within a loop or for a large batch of users. In order to get all groups for a user, each group must be enumerated to get that groups group recursively until exhausted. These enumerations are done recursively with additional ldapjs clients as needed. In addition, if a result uses RangeRetrieval attributes, those are also recursively called asynchronously with additional ldapjs clients.

I run this module on a ActiveDirectory installation with over 15000 users... and over 1000+ groups which are heavily nested.

**Comment by bibodha** [comment]
Thanks for the prompt reply. Here is the piece of code I'm running:

```    
app.use(function (req, res, next) {
  if (!req.session.user) {
    var ntlmUserName = ''; //ntlm username here
    var group = ''; //group here
    console.log('ntlmUserName: ', ntlmUserName);
    console.log('group: ', group);
    activedirectory.findUser({includeMembership: ['user']}, ntlmUserName, function (err, user) {
      if (err) {
        res.status(500).send('Cannot connect to active directory: ' + err);
      } else {
        console.log(user);
        console.log(user.groups);
        user.groups = user.groups.map(function (item) { return item.cn; });
        if (user.groups.indexOf(group) !== -1) {
          req.session.user = user;
          next();
        } else {
          res.status(403).send('Forbidden');
        }
      }
    });
  } else {
    next();
  }
});
```
This is the config for connection
```
      connection: {
        url: 'ldap://url.com',
        baseDN: 'dc=domain,dc=com',
        username: 'service-account',
        logging: {
          name: 'activedirectory',
          streams: [{
            level: 'trace',
            path: 'ad.json'
          }]
        }
      },
      allowedgroup: 'group-to-find'

```
the password is being set on the environment variable for the service account.


This comes back for my username and in the log it says I have 433 nested groups. It finds the group that I am looking for but the only problem is it's called the callback function with the error long before this has completed. I don't have any other for loops or anything. I'm not sure about the hardware that's running the domain controller since it's all handled by IT and i don't have access to it. I can try and find out but my confusion comes from this working on windows with exact same node version but not working on mac. I have tried to hammer the domain controller from my windows machine and it doesn't even flinch, comes back 100% of the time but on the mac side, it fails 100% of the time.

**Comment by gheeres** [comment]
Where you able to get this resolved?

**Comment by bibodha** [comment]
no, i haven't had time to dive into this. I switched from node to .net :( I'll look into this some more later when I have a little bit more free time.

**Comment by kheide** [comment]
FWIW I have this issue aswell and it's painstakingly annoying.
