### ISSUE TITLE
code":49, 52e

### ISSUE THREAD

**Issue by chundemer** [gheeres/node-activedirectory#23]
The username/password for the admin LDAP config is correct. IDEAS, SUGGESTIONS?

``` javascript
var ad = new ActiveDirectory({ url: 'LDAP://LDAPAUTH.LDAP.< MYDOMAIN >.org',
        baseDN: 'OU=SystemUsers,DC=< OUR >,DC=< DOMAIN >DC=local',
        username: '< VALIDUSER >',
        password: ' <VALID PASSWORD>' });

    var username = '< TESTUSERNAME >' ;
    var password = '< TESTPASSWORD >' ;

    ad.authenticate(username, password, function(err, auth) {
        if (err) {
            console.log('ERROR: '+JSON.stringify(err));
            return;
        }

        if (auth) {
            console.log('Authenticated!');
        }
        else {
            console.log('Authentication failed!');
        }
    });
```

```
ERROR: {"dn":"","code":49,"name":"InvalidCredentialsError","message":"80090308: LdapErr: DSID-0C0903A8, comment: AcceptSecurityContext error, data 52e, v1db1\u0000"}
```

**Comment by AkramBerkawy** [comment]
I have special characters in my password how do I escape it?

**Comment by gheeres** [comment]
This is likely an upstream issue. But I'll try to help you.
Can you give an example of what you mean by a special character?

i.e. ASCII 0x13

**Comment by sgtquezada** [comment]
I apologize for piggy backing off this old thread but this is the only thread I see referencing the specific LDAP error that I am also seeing when trying to use this module.  I am specifically trying to understand if the issue is with the password for the bindDN (AD admin user account) and itself having special characters or if the issue is actually with special characters that the user's password has (via the login form).  I am using passport and combining this module within the authentication call.

**Comment by gheeres** [comment]
To see if the problem is with the bindDN (used for searching, etc.), just configure and issue a findUser() or other API method call. If it works, then the problem is NOT with the AD admin user account.
