### ISSUE TITLE
trouble authenticating

### ISSUE THREAD

**Issue by nev-dru** [gheeres/node-activedirectory#60]
I am having trouble authenticating and have tried several configurations. Not sure what I am doing wrong. I keep getting 
<code>
ERROR: {"dn":"","code":49,"name":"InvalidCredentialsError","message":"80090308: LdapErr: DSID-0C0903C5, comment: AcceptSecurityContext error, data 52e, v2580\u0000"}
</code>

I really only need the ability to determine if an email is a group email, and if so, get all the emails associated with that group. 
Is it required that you pass in admin user credentials? in the config for: 
<code>
var ad = new ActiveDirectory(config);
</code>

I have a password (and no username) that is used to access Active directory using npm ldap, for authenticating users name/password at login for the app. But it seems that activedirectory requires an admin username in the config, which I don't have.

**Comment by gheeres** [comment]
There is the ad.authenticate(username, password) method which checks to see if the username and password are valid. This is done with a "bind" using the specified credentials. If this is the only call you're making to your ad object, then you DO NOT need to specify the username/password in the configuration. 

For all of the other search, find, etc. methods, the username/password MUST be specified in the ad configuration when the object is configured. This account obviously needs permission to read the specified attributes. Typically this is a preconfigured account that you use for reading your AD data. It's typically NOT based on the user who's information you are attempting to retrieve.

>I really only need the ability to determine if an email is a group email, and if so, get all the emails associated with that group.  Is it required that you pass in admin user credentials?

For this usage, YES, you need to configure the admin account (or an account that has permissions to read the attributes that you want).

>I have a password (and no username) that is used to access Active directory using npm ldap, for authenticating users name/password at login for the app.

For authentication (binding), you don't need an admin username or password. For retrieving any properties for the user, YES, you need an admin username and password. Just a password by itself will NOT work (for anything related to AD or LDAP). It's possible that if you still have access to the original username / password for the user, you can use that for your admin username/password when you create your AD object. That SHOULD work because the account should be able to read all of the properties for itself. 

I can't be more specific without knowing more about your workflow.

**Comment by gheeres** [comment]
Also when authenticating, you need to make sure you are binding with information in either of the following formats:

```
DOMAIN\username
username@domain.com
```

Just using the sAMAccountName (username) by itself will NOT work.

**Comment by nev-dru** [comment]
Thank You! that was very helpful. This item be closed.
