### ISSUE TITLE
is open ldap supported?

### ISSUE THREAD

**Issue by GiladShoham** [gheeres/node-activedirectory#66]
hi,
we have a customer which use open ldap.
do you know if open ldap should be supported by the library?
did you try it maybe?

thx.

**Comment by gheeres** [comment]
Internally this modules uses ldapjs which should support openldap. However, with openldap there is no "one" way to create your schema, it's more open ended. node-activedirectory is Microsoft specific. Some of the attribute names and extensions used by ActiveDirectory are Microsoft specific and likely not used by an openldap installation. So it really doesn't make sense to use it for those purposes.

If you need to support both, I would create a custom wrapper for ldapjs that mimics the node-activedirectory API and then you can swap the implementations based on the user.

**Comment by GiladShoham** [comment]
Thx!
do you know maybe to specify specific stuff - functions / attributes / plugins that doesn't work with open ldap?
maybe if i won't use them i can partially support open ldap? 
or i really need to write a full wrapper? 
is there a point to try it with node-ad?

**Comment by gheeres** [comment]
ActiveDirectory resolves around the concept of Users and Groups. Technically you only need to support the functions that you've used from ActiveDirectory. If you implement all of the same functions with the same parameters, then you should be able to drop in the OpenLdap implementation with minimal code change. Essentially, create an common "Interface" for the two implementations and then write to that interface. Of course JavaScript isn't strongly typed so there isn't an official "interface" keyword, etc. The prototype methods are probably as close as you can get to an interface with JavaScript. What you could do is to inherit your custom class from ActiveDirectory and then override the prototypes that require different functionality.

To write your implementation, you'll probably need to dive into LDAP and understand it a little more. If you're planning on supporting multiple customers with OpenLDAP, you'll need to make it VERY extensible because there is NO guarantee that the attributes used in one OpenLDAP installation correspond to another. If you're lucky, they're using the standard [InetOrgPerson](https://tools.ietf.org/html/rfc2798) implementation. Group mapping will be more difficult since there isn't an RFC that I'm aware of. Hopefully they're using member / memberOf attributes. There is no one way or right way to configure and setup OpenLDAP.

See the following Stackoverflow post that goes into a little more detail: http://stackoverflow.com/questions/20397852/inetorgperson-with-member-or-memberof

**Comment by GiladShoham** [comment]
Thx a lot for your detailed answer.
if we will decide to support them both i will dig deeper to this.
