### ISSUE TITLE
Workaround for ldapjs error?

### ISSUE THREAD

**Issue by frebos88** [gheeres/node-activedirectory#68]
The dependency ldapjs is throwing errors when trying to use secure ldap. Issue can be found here: https://github.com/mcavage/node-ldapjs/issues/245

Is it possible to work around this issue?

**Comment by gheeres** [comment]
As per the issue, the problem 'IS' fixed in the main branch. An automatic fix isn't available until the author of ldapjs publishes a new release.

One work around is to manually update the version of ldapjs that activedirectory is using. Go into your _node_modules/activedirectory/node_modules/_ folder. In there should be a _ldapjs/_ folder. Replace contents of that folder with the contents of the [_lib/_](https://github.com/mcavage/node-ldapjs/tree/master/lib) folder from the ldapjs github main branch.

```
cd node_modules/activedirectory/node_modules/
rm -rf ldapjs
git clone https://github.com/mcavage/node-ldapjs.git ldapjs-source
ln -sf ldapjs-source/lib ldapjs
``` 
The above commands are linux specific. 

But essentially you want to replace the contents of your ldapjs folder with the contents of the _lib/_ folder from the ldapjs GitHub main branch. Manually downloading, copying and pasting on a Windows box will also work.

**Comment by jsumners** [comment]
Or install ldapjs prior to (as a top level dependency) ActiveDirectory -- `npm install --save mcavage/node-ldapjs`

**Comment by gheeres** [comment]
Has the main branch for ldapjs been published / updated now? If so, I'll test and update the package.json to include the latest version.

**Comment by jsumners** [comment]
Not that I'm aware of. I really wish there were a better alternative to
ldapjs. But your library works wonderfully for what I needed to do. Thank
you for that.

On Thursday, July 23, 2015, George Heeres <notifications@github.com> wrote:

> Has the main branch for ldapjs been published / updated now? If so, I'll
> test and update the package.json to include the latest version.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gheeres/node-activedirectory/issues/68#issuecomment-124130181>
> .
>


-- 
James Sumners
http://james.sumners.info/ (technical profile)
http://jrfom.com/ (personal site)
http://haplo.bandcamp.com/ (band page)
